theme: minima
title: Share what you made.
author: Crazy-eye Eddie
email: eddie@crazy.com
description: > # this means to ignore newlines until "baseurl:"
  Track your creations in the Registry.
  You create the value we use to build the future.
  Add your assets here so they're discoverable for proposals and projects.

# social links
twitter_username: eddie-twitter
github_username:  eddie-github

show_excerpts: true # set to false to remove excerpts on the homepage
